name: CMake build, test & package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake dpkg-dev g++-13 libboost-dev libcurl4-openssl-dev

    - name: configure, build, test and package
      run: cmake --workflow --preset ci

    - name: inspect Debian package
      run: |
        dpkg-deb --info build/ci/packages/*.deb
        dpkg-deb --contents build/ci/packages/*.deb
