name: Scoreo2 build & package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install deps
      run: |
        sudo apt update
        sudo apt install -y libboost-dev

    - name: build
      run: ./bootstrap.sh
